# -*- coding: utf-8 -*-
"""IMAGE AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fS4ittC3e2O5YEOrbdTcbBEMGJW1DPwb
"""

!pip install --upgrade diffusers transformers torch accelerate """ INSTALLING  ALL THE LIBRARIES"""
!pip install Pillow
!pip install accelerate

from diffusers import StableDiffusionPipeline #IMPORTING ALL MODULES
import torch
import matplotlib.pyplot as plt
from PIL import Image
#LOADING THE MODEL
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16 ,safety_checker = None, requires_safety_checker = False)
pipe = pipe.to(device)
#GENERATIN THE IMAGE
def generate_image(prompt, num_inference_steps=50, guidance_scale=7.5):
    with torch.autocast("cuda"):
        image = pipe(prompt, num_inference_steps=num_inference_steps, guidance_scale=guidance_scale).images[0]
    return image

# Example usage
prompt = "a porche"
generated_image = generate_image(prompt)

# Display the generated image
plt.imshow(generated_image)
plt.axis("off")  # Hide the axes
plt.show()

